### ISSUE TITLE
code blockchain by POS and go-libp2p

### ISSUE THREAD

**Issue by bob2325168** [mycoralhealth/blockchain-tutorial#30] opened 2020-03-25 06:25 UTC
hello, I want to know how to code blockchain with POS and go-libp2p, that's cool for me. If you have demo, I would be grateful.

**Comment by nosequeldeebee** [comment] 2021-03-27 22:29
not a bug or specific feature request. Closing issue

**Closed as completed by nosequeldeebee** 2021-03-27 22:29 UTC
Labels: enhancement
