### ISSUE TITLE
another problem in windows10 terminal

### ISSUE THREAD

**Issue by xuanyuan33521** [mycoralhealth/blockchain-tutorial#36] opened 2020-10-09 09:00 UTC
when print "70",in windows terminal ,you well see"strconv.Atoi:"70/r" invalid sy
the renson is windows system "Enter" key is"/r" in end.
so change you code in 179 line like this:
sendData = strings.Replace(sendData, "\r", "", -1)

**Comment by nosequeldeebee** [comment] 2021-03-27 22:29
feel free to submit a PR if you wish. This is a duplicate of #23

**Closed as completed** 2021-04-05 02:48 UTC
